# Generated by Django 6.0.5 on 2026-05-10 07:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='暱稱')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=50, verbose_name='章節')),
                ('question_number', models.IntegerField(verbose_name='題號')),
                ('question_text', models.TextField(verbose_name='題目')),
                ('option_a', models.CharField(max_length=500, verbose_name='選項A')),
                ('option_b', models.CharField(max_length=500, verbose_name='選項B')),
                ('option_c', models.CharField(max_length=500, verbose_name='選項C')),
                ('option_d', models.CharField(blank=True, max_length=500, null=True, verbose_name='選項D')),
                ('option_e', models.CharField(blank=True, max_length=500, null=True, verbose_name='選項E')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='正確答案')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], default='medium', max_length=10, verbose_name='難易度')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'ordering': ['chapter', 'question_number'],
                'unique_together': {('chapter', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=50, verbose_name='章節')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('correct_count', models.IntegerField(verbose_name='答對題數')),
                ('score', models.FloatField(verbose_name='分數')),
                ('time_spent', models.IntegerField(default=0, verbose_name='耗時(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '作答記錄',
                'verbose_name_plural': '作答記錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=1, verbose_name='使用者答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question', verbose_name='題目')),
                ('quiz_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizrecord', verbose_name='作答記錄')),
            ],
            options={
                'verbose_name': '錯題記錄',
                'verbose_name_plural': '錯題記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
