# Generated by Django 6.0.5 on 2026-05-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sequence_group',
            field=models.CharField(blank=True, help_text='同一組別的題目會保持順序', max_length=50, null=True, verbose_name='連貫題組別'),
        ),
    ]
