# Generated by Django 6.0.5 on 2026-05-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_sequence_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_app/images/', verbose_name='題目圖片'),
        ),
    ]
