# Generated by Django 6.0.5 on 2026-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='自編題目'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_note',
            field=models.CharField(blank=True, help_text='若為自編題目，請註明來源或設計說明', max_length=200, verbose_name='題目來源'),
        ),
    ]
