# Generated by Django 6.0.5 on 2026-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_question_is_new_question_source_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='作答後顯示的詳細解析，說明為什麼正確答案是對的', verbose_name='題目詳解'),
        ),
        migrations.AddField(
            model_name='quizrecord',
            name='is_sr',
            field=models.BooleanField(default=False, verbose_name='間隔學習法'),
        ),
    ]
