# Generated by Django 6.0.5 on 2026-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_question_explanation_quizrecord_is_sr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='班級'),
        ),
    ]
