# Generated by Django 6.0.5 on 2026-06-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_user_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='累計錯誤次數'),
        ),
        migrations.AddField(
            model_name='question',
            name='total_attempt_count',
            field=models.IntegerField(default=0, verbose_name='累計答題次數'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='教師身分'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班級名稱')),
                ('invite_code', models.CharField(max_length=20, unique=True, verbose_name='邀請碼')),
                ('description', models.TextField(blank=True, verbose_name='班級描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='教師')),
            ],
            options={
                'verbose_name': '班級',
                'verbose_name_plural': '班級',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quiz_app.classroom', verbose_name='班級')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '班級成員',
                'verbose_name_plural': '班級成員',
                'ordering': ['joined_at'],
                'unique_together': {('classroom', 'student')},
            },
        ),
    ]
